services:
  App\Scheduler\DbScheduleProvider:
    tags: ['scheduler.schedule_provider']
  App\Scheduler\MetricsScheduleProvider:
    tags: ['scheduler.schedule_provider']
  App\Scheduler\NotificationsScheduleProvider:
    tags: ['scheduler.schedule_provider']
