# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Trust proxies (Render uses a proxy in front of the app)
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port']

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 3600
        gc_maxlifetime: 3600

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
